-- ============================================
-- FACT TABLE: Transaction Records
-- ============================================
CREATE TABLE IF NOT EXISTS fact_transactions (
    id SERIAL PRIMARY KEY,
    transaction_id VARCHAR(100) UNIQUE NOT NULL,
    external_order_id VARCHAR(100),
    order_id VARCHAR(100),
    payment_id VARCHAR(100),
    
    -- Financial Data
    total_cost DECIMAL(15, 2) NOT NULL,
    payment_status VARCHAR(50) DEFAULT 'PENDING',
    payment_method VARCHAR(50),
    currency VARCHAR(10) DEFAULT 'IDR',
    
    -- Stock Data (stored as JSONB for flexibility)
    stock_before JSONB,
    stock_after JSONB,
    
    -- Metadata
    source_system VARCHAR(100),
    request_payload JSONB,
    response_payload JSONB,
    error_details TEXT,
    
    -- Timestamps
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    payment_completed_at TIMESTAMP,
    
    -- Soft delete
    is_deleted BOOLEAN DEFAULT FALSE
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_transaction_id ON fact_transactions(transaction_id);
CREATE INDEX IF NOT EXISTS idx_external_order ON fact_transactions(external_order_id);
CREATE INDEX IF NOT EXISTS idx_payment_status ON fact_transactions(payment_status);
CREATE INDEX IF NOT EXISTS idx_created_at ON fact_transactions(created_at);
CREATE INDEX IF NOT EXISTS idx_source_system ON fact_transactions(source_system);

-- Comments
COMMENT ON TABLE fact_transactions IS 'Central fact table storing all transaction lifecycle data from order creation to payment completion';
COMMENT ON COLUMN fact_transactions.transaction_id IS 'Unique transaction identifier generated by this service';
COMMENT ON COLUMN fact_transactions.external_order_id IS 'Order ID from external system (e.g., mobile app, web)';
COMMENT ON COLUMN fact_transactions.stock_before IS 'Stock levels before transaction (JSONB)';
COMMENT ON COLUMN fact_transactions.stock_after IS 'Stock levels after payment success (JSONB)';

-- ============================================
-- AUDIT LOG TABLE
-- ============================================
CREATE TABLE IF NOT EXISTS audit_logs (
    id SERIAL PRIMARY KEY,
    transaction_id VARCHAR(100),
    action VARCHAR(50) NOT NULL,
    actor VARCHAR(100),
    details JSONB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT fk_transaction
        FOREIGN KEY(transaction_id) 
        REFERENCES fact_transactions(transaction_id)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_audit_transaction ON audit_logs(transaction_id);
CREATE INDEX IF NOT EXISTS idx_audit_created ON audit_logs(created_at);
CREATE INDEX IF NOT EXISTS idx_audit_action ON audit_logs(action);

COMMENT ON TABLE audit_logs IS 'Audit trail for all transaction state changes';

-- ============================================
-- INTEGRATION STATUS TABLE
-- ============================================
CREATE TABLE IF NOT EXISTS integration_status (
    id SERIAL PRIMARY KEY,
    transaction_id VARCHAR(100),
    service_name VARCHAR(50) NOT NULL,
    status VARCHAR(50) NOT NULL,
    request_data JSONB,
    response_data JSONB,
    error_message TEXT,
    retry_count INT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT fk_integration_transaction
        FOREIGN KEY(transaction_id) 
        REFERENCES fact_transactions(transaction_id)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_integration_transaction ON integration_status(transaction_id);
CREATE INDEX IF NOT EXISTS idx_integration_service ON integration_status(service_name);
CREATE INDEX IF NOT EXISTS idx_integration_status ON integration_status(status);

COMMENT ON TABLE integration_status IS 'Tracking status of external service integrations (Order, Payment, Inventory)';

-- ============================================
-- TRIGGER: Auto-update updated_at
-- ============================================
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_fact_transactions_updated_at 
    BEFORE UPDATE ON fact_transactions 
    FOR EACH ROW 
    EXECUTE FUNCTION update_updated_at_column();

-- ============================================
-- VIEWS: Reporting & Analytics
-- ============================================

-- View: Transaction Summary
CREATE OR REPLACE VIEW v_transaction_summary AS
SELECT 
    DATE(created_at) as transaction_date,
    source_system,
    payment_status,
    COUNT(*) as transaction_count,
    SUM(total_cost) as total_amount,
    AVG(total_cost) as avg_amount
FROM fact_transactions
WHERE is_deleted = FALSE
GROUP BY DATE(created_at), source_system, payment_status
ORDER BY transaction_date DESC;

COMMENT ON VIEW v_transaction_summary IS 'Daily summary of transactions by source and status';

-- View: Service Integration Health
CREATE OR REPLACE VIEW v_integration_health AS
SELECT 
    service_name,
    status,
    COUNT(*) as call_count,
    MAX(created_at) as last_call,
    AVG(retry_count) as avg_retry
FROM integration_status
WHERE created_at > NOW() - INTERVAL '24 hours'
GROUP BY service_name, status
ORDER BY service_name, status;

COMMENT ON VIEW v_integration_health IS 'Health metrics for external service integrations in last 24 hours';

-- ============================================
-- INITIAL TEST DATA (Optional for development)
-- ============================================
-- Uncomment below to insert test data

/*
INSERT INTO fact_transactions (
    transaction_id, external_order_id, order_id,
    total_cost, payment_status, source_system,
    request_payload
) VALUES 
(
    'TXN-TEST-001',
    'EXT-TEST-001',
    'ORD-TEST-001',
    150000,
    'SUCCESS',
    'TEST_SYSTEM',
    '{"items": [{"product_id": "PROD-001", "quantity": 2, "price": 75000}]}'::jsonb
),
(
    'TXN-TEST-002',
    'EXT-TEST-002',
    'ORD-TEST-002',
    250000,
    'PENDING',
    'TEST_SYSTEM',
    '{"items": [{"product_id": "PROD-002", "quantity": 1, "price": 250000}]}'::jsonb
);
*/

-- ============================================
-- SUCCESS MESSAGE
-- ============================================
DO $$
BEGIN
    RAISE NOTICE '✅ Database schema initialized successfully!';
    RAISE NOTICE '📊 Tables created: fact_transactions, audit_logs, integration_status';
    RAISE NOTICE '📈 Views created: v_transaction_summary, v_integration_health';
END $$;